import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/ui/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="flex justify-center ">
          <div className="flex flex-col gap-4 w-[794px] min-h-[1123px] mx-auto py-8">
            <Nav/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
